### ISSUE TITLE
[TypeError: Cannot set property length of [object Object] which has only a getter]

### ISSUE THREAD

**Issue by Harsha509** [DataGarage/node-xls-json#14]
npm module "xsl-to-json" worked fine ,but after few days am having this error while running the same scripts. The error observed when i have upgraded the node V to 4.2.2 , previously i was using 0.12.0 node version

C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\dist\cpexcel.js:904
        mdb.length = 2 \* len;
                   ^

TypeError: Cannot set property length of [object Object] which has only a getter
    at sbcs_d (C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\dist\cpexcel.js:904:20)
    at Object.decode 
(C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\dist\cpexcel.js:1187:40)
    at _gc2 (C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\xls.js:19:23)
    at Buffer.ReadShift [as read_shift](C:usersadmindesktopprojectnode_modulesxls-to-jsonnode_modulesxlsjsxls.js:178:13)
    at parse_XLUnicodeStringNoCch (C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\xls.js:1779:36)
    at parse_XLUnicodeString (C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\xls.js:1788:9)
    at Object.parse_WriteAccess [as f](C:usersadmindesktopprojectnode_modulesxls-to-jsonnode_modulesxlsjsxls.js:2059:17)
    at slurp (C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\xls.js:5411:11)
    at parse_workbook (C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\xls.js:5509:15)
    at parse_xlscfb (C:\users\admin\desktop\project\node_modules\xls-to-json\node_modules\xlsjs\xls.js:5944:27)

**Comment by drorn-aprcd** [comment]
I have the exact same error...

**Comment by nathanmalishev** [comment]
Also have this error

**Comment by Mad-Head** [comment]
Also have this error

**Comment by parthivpn** [comment]
Me too have above error. please help me to recover from this

**Comment by dani3l** [comment]
same here

**Comment by LingJiJian** [comment]
same here + 1

**Comment by dchambers** [comment]
Just ran into the exact same issue.

This bug is actually an issue with an upstream dependency ([xlsjs](https://www.npmjs.com/package/xlsjs)) rather than an issue with this package _per se_. I can see that it works in Node.js 0.12.11 but fails in the subsequent version &mdash; Node.js 4.0.0. It looks like the `length` property of `Buffer` was not something you were meant to write to even in 0.12.x:

  * https://nodejs.org/docs/v0.4.4/api/buffers.html#buffer.length

but that this formally became a read-only property in subsequent releases:

  * https://nodejs.org/api/buffer.html#buffer_buf_length

Actually, it's not obvious to me that this line of code will ever have had any practical effect:

~~~js
mdb.length = 2 * len;
~~~

and in fact commenting this line of code out allows me to run our code with no obvious repercussions.

**Comment by pranavmayuram** [comment]
Has this change been added to a new release?

**Comment by rodrigograca31** [comment]
In a couple of minute I will merge #15 and maybe this problem gets solved...

**Comment by rodrigograca31** [comment]
Can anyone confirm if this is solved?

**Comment by rodrigograca31** [comment]
Its working on v0.12.7

**Comment by Jasnan** [comment]
I have tested it on `v0.12.4`, `v5.11.1`, `v6.8.0`, `v7.0.0`. Its working on all these versions. Please close the issue.
